package generate

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"tervdocs/internal/config"
	"tervdocs/internal/providers"
)

type fakeProvider struct{}

func (f fakeProvider) Name() string    { return "fake" }
func (f fakeProvider) Validate() error { return nil }
func (f fakeProvider) Generate(_ context.Context, _ providers.Request) (providers.Response, error) {
	return providers.Response{
		Content:  "# Demo\n\nGenerated by fake provider.\n",
		Provider: "fake",
		Model:    "fake-model",
	}, nil
}

func TestRunWithProviderFactory(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module demo\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "main.go"), []byte("package main\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cfg := config.Default()
	cfg.Provider = "free"
	cfg.Output.File = "README.test.md"

	svc := NewServiceWithProviderFactory(func(name string, cfg config.Config) (providers.Provider, error) {
		return fakeProvider{}, nil
	})
	res, err := svc.Run(context.Background(), cfg, Options{RootDir: root})
	if err != nil {
		t.Fatalf("run failed: %v", err)
	}
	if res.OutputPath == "" {
		t.Fatalf("expected output path")
	}
	b, err := os.ReadFile(filepath.Join(root, "README.test.md"))
	if err != nil {
		t.Fatalf("read output failed: %v", err)
	}
	if string(b) == "" || b[0] != '#' {
		t.Fatalf("unexpected output content")
	}
}
